### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by dvor** [sbotichelli/BusTracker#2]
We would like to use [Travis CI](https://travis-ci.org/) as a continuous integration server.

Link Travis to the repo and add `.travis.yml` file with build instruction. Travis should build app and run unit tests.

- Travis docs for integration with Swift projects https://docs.travis-ci.com/user/languages/objective-c/
- Tutorial on integrating Travis, might be useful https://www.raywenderlich.com/1618-travis-ci-tutorial-getting-started#c-rate

**Comment by sbotichelli** [comment]
Travis has been launched for a project.
